### ISSUE TITLE
PlantIT is not finding my plantit.yaml file

### ISSUE THREAD

**Issue by Chris-Schnaufer** [Computational-Plant-Science/plantit#230]
The file is located at https://github.com/AgPipeline/drone-makeflow/blob/main/plantit.yaml. All branches of this project have the YAML file.

When I scan for workflows I get a message saying that there aren't any `plantit.yaml` files. My GitHub account name is `Chris-Schnaufer`
<img width="803" alt="Screen Shot 2021-11-05 at 2 10 50 PM" src="https://user-images.githubusercontent.com/45463434/140579064-5cc1e7e7-9741-4896-aaa7-e1be8eb97d42.png">

I have also tried logging out and back in with no change in the result.

Previously, before I merged into the main branch, the YAML file was found, but it appeared that the file couldn't be loaded from that branch and an error was reported. This problem occurred after I merged to the main branch and removed the branch that the YAML file had originally been on.

**Comment by w-bonelli** [comment]
Hi @Chris-Schnaufer, thanks for reporting this. Looks like a regression introduced in v0.0.30:

```
[2021-11-09 08:19:53,526: ERROR/ForkPoolWorker-1] Task plantit.celery_tasks.refresh_personal_workflows[5b8534fc-ada7-485b-915f-995a8f73965c] raised unexpected: TypeError("argument of type 'TypeError' is not iterable")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/plantit/plantit/celery_tasks.py", line 443, in refresh_personal_workflows
    async_to_sync(refresh_personal_workflow_cache)(owner)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 223, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 292, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/code/plantit/plantit/utils.py", line 421, in refresh_personal_workflow_cache
    tasks = await asyncio.gather(*[
  File "/code/plantit/plantit/utils.py", line 388, in workflow_to_dict
    bundle = await github.get_repo_bundle(
  File "/code/plantit/plantit/github.py", line 284, in get_repo_bundle
    valid = validate_repo_config(config, cyverse_token)
  File "/code/plantit/plantit/github.py", line 22, in validate_repo_config
    if 'name' not in config:
TypeError: argument of type 'TypeError' is not iterable
```

Working on a test case and fix

**Comment by Chris-Schnaufer** [comment]
I am still not able to run any tasks since it appears that the YAML file is not found: https://github.com/Chris-Schnaufer/drone-makeflow

**Comment by w-bonelli** [comment]
Hi @Chris-Schnaufer, yesterday's patch should address this. YAML files no longer need to be bound explicitly - they should be automatically detected and shown. There is also a new dropdown option on the Workflows page to view organization-owned repositories. These are also automatically scraped from GitHub.

Are you able to see your repositories in the Workflows view now? Sorry again for the delay in fixing this.

**Comment by Chris-Schnaufer** [comment]
@w-bonelli I am still having problems - primarily I am unable to start Tasks. 

The Workflow reports that I don't have any:
<img width="1076" alt="Screen Shot 2021-12-19 at 9 27 53 AM" src="https://user-images.githubusercontent.com/45463434/146678577-baacf95f-f946-47d0-b921-92423f8cf29f.png">

But, I am able to connect to AgPipeline where it shows two options [link to project](https://github.com/AgPipeline/drone-makeflow):
<img width="1008" alt="Screen Shot 2021-12-19 at 9 28 12 AM" src="https://user-images.githubusercontent.com/45463434/146678582-f1f3fc03-1bc3-4571-b482-41bf4e1272dc.png">

For Tasks, I don't have the option to run one, even though the YAML file exists:
<img width="802" alt="Screen Shot 2021-12-19 at 9 29 02 AM" src="https://user-images.githubusercontent.com/45463434/146678627-ac4f439e-f8a9-48f7-9d7b-a702bd31bcd7.png">

**Comment by w-bonelli** [comment]
Apologies @Chris-Schnaufer, the unnamed workflows should be selectable now: if you click the placeholder "name not provided" link it should open a detail view. Then if you select Submit it will show a submission menu, e.g. (my reproduction):
<img width="1286" alt="Screen Shot 2021-12-20 at 6 42 47 PM" src="https://user-images.githubusercontent.com/10502868/146847123-3426971c-1983-4941-9368-d662c07e0d68.png">

Adding a `name` attribute to your `plantit.yaml` will remove the warning message and display the value of that attribute instead. (Workflows are refreshed every 5 minutes so the update will take a brief period to register in the UI.)

Looks like the repositories shown in the AgPipeline context are the two branches of the [drone-makeflow repo](https://github.com/AgPipeline/drone-makeflow). If you have personal forks of these we unfortunately can't access them yet due to limitations of the Github API. Any non-fork public repos with `plantit.yaml` files in any branch should be visible, though - let me know if this is not the case.

The public Stampede2 agent should be listed as a submission target. Just confirmed it is working for our test pipeline but if you encounter submission failures please let me know and happy to help debug.

**Comment by w-bonelli** [comment]
Workflow integration seems to be working correctly now but please feel free to reopen if there are any more issues
