### ISSUE TITLE
Cannot create workflow 

### ISSUE THREAD

**Issue by jsab101** [Computational-Plant-Science/plantit#367]
There is no "workflow" tab accessible anywhere on the website. I have a cyverse account and cannot submit a workflow from there either. I have also tried https://plantit.cyverse.org/apis/v1/workflows/ which also does not allow me to submit a workflow 

plantit.cyverse.org: 
![Screen Shot 2023-11-09 at 4 03 27 PM](https://github.com/Computational-Plant-Science/plantit/assets/150392036/30b7caab-4564-4e17-b972-1ee050abd4ec)

cyverse: 
![Screen Shot 2023-11-09 at 4 12 52 PM](https://github.com/Computational-Plant-Science/plantit/assets/150392036/84592340-2444-4e0b-810f-f1ea5d5f9a82)

https://plantit.cyverse.org/apis/v1/workflows/
![Screen Shot 2023-11-09 at 4 14 35 PM](https://github.com/Computational-Plant-Science/plantit/assets/150392036/1ab1611a-e1b3-41c2-a7fa-f43968a29f60)

**Comment by koalaspirit** [comment]
Hi,You must login with your cyverse account——“Work for a cause, not for applause. Live life to express, not to impress. Don’t strive to make your presence noticed, just make your absence felt.” - unknown On Nov 9, 2023, at 2:16 PM, jsab101 ***@***.***> wrote:﻿
There is no "workflow" tab accessible anywhere on the website. I have a cyverse account and cannot submit a workflow from there either. I have also tried https://plantit.cyverse.org/apis/v1/workflows/ which also does not allow me to submit a workflow
plantit.cyverse.org:

cyverse:

https://plantit.cyverse.org/apis/v1/workflows/

**Comment by jsab101** [comment]
Hi, 

this is what it looks like when I login, there is still no place to submit a workflow 
![Screen Shot 2023-11-13 at 8 54 38 AM](https://github.com/Computational-Plant-Science/plantit/assets/150392036/c5e23d19-7000-4ba8-b73f-d5bbdd9e222e)



> Hi,You must login with your cyverse account——“Work for a cause, not for applause. Live life to express, not to impress. Don’t strive to make your presence noticed, just make your absence felt.” - unknown On Nov 9, 2023, at 2:16 PM, jsab101 ***@***.***> wrote:﻿ There is no "workflow" tab accessible anywhere on the website. I have a cyverse account and cannot submit a workflow from there either. I have also tried https://plantit.cyverse.org/apis/v1/workflows/ which also does not allow me to submit a workflow plantit.cyverse.org: cyverse: https://plantit.cyverse.org/apis/v1/workflows/ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by koalaspirit** [comment]
That is a browser issue. What browser do you use?——“Work for a cause, not for applause. Live life to express, not to impress. Don’t strive to make your presence noticed, just make your absence felt.” - unknown On Nov 13, 2023, at 6:56 AM, jsab101 ***@***.***> wrote:﻿
Hi,
this is what it looks like when I login, there is still no place to submit a workflow


Hi,You must login with your cyverse account——“Work for a cause, not for applause. Live life to express, not to impress. Don’t strive to make your presence noticed, just make your absence felt.” - unknown On Nov 9, 2023, at 2:16 PM, jsab101 @.> wrote:﻿ There is no "workflow" tab accessible anywhere on the website. I have a cyverse account and cannot submit a workflow from there either. I have also tried https://plantit.cyverse.org/apis/v1/workflows/ which also does not allow me to submit a workflow plantit.cyverse.org: cyverse: https://plantit.cyverse.org/apis/v1/workflows/ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>

**Comment by koalaspirit** [comment]
Simply hit the back button until you are on the Home Screen again and press login again. If that does not work, then you have  modified the standard browser settings and I can not help you.  You are definitely logged in according to your screenshot. However, the redirect to the webpage is stuck and that's why you end up in the key cloak menu. Keycloak is not PlantIT but the authentication service of CyVerse.

**Comment by jsab101** [comment]
The login button wasn't present on my home screen until one day it was, clicking it solved the problem.
